//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_Management_System.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatInfo
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> SeatNo { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> TransportId { get; set; }
        public Nullable<int> AgeClass { get; set; }
        public Nullable<int> SeatClass { get; set; }
    
        public virtual AgeClassEnum AgeClassEnum { get; set; }
        public virtual PurchasedTicket PurchasedTicket { get; set; }
        public virtual SeatClassEnum SeatClassEnum { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
