//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_Management_System.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Emails = new HashSet<Email>();
            this.Phones = new HashSet<Phone>();
            this.PurchasedTickets = new HashSet<PurchasedTicket>();
            this.Transports = new HashSet<Transport>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> FamilyId { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> Role { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual Family Family { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual ICollection<PurchasedTicket> PurchasedTickets { get; set; }
        public virtual UserRoleEnum UserRoleEnum { get; set; }
        public virtual ICollection<Transport> Transports { get; set; }
    }
}
